/*
------------------------------------------------------------------------------------------------------------------------
-- SCRIPT INFORMATION BLOCK
------------------------------------------------------------------------------------------------------------------------

-- FILE NAME:                 stage_schema
-- DESCRIPTION:               Creación de esquema de base de datos para proceso de limpieza de datos, transformaciones y limpieza desde capa RAW
-- DATABASE PLATFORM:         PostgreSQL
-- DATABASE VERSION:          PostgreSQL 17

-- AUTHOR:                    ITMEET
-- CREATION DATE:             2025-11-20

------------------------------------------------------------------------------------------------------------------------
-- VERSION CONTROL & HISTORY
------------------------------------------------------------------------------------------------------------------------

-- VERSION:                   1.0.0
-- LAST MODIFIED BY:          ITMEET
-- LAST MODIFIED DATE:        2025-11-20
-- CHANGE LOG:                - Creación inicial del script para establecer el esquema de la base de datos de Stage.

------------------------------------------------------------------------------------------------------------------------
-- EXECUTION & DEPENDENCIES
------------------------------------------------------------------------------------------------------------------------

-- TARGET OBJECT(S):          
-- PRE-REQUISITES:            Capa RAW debe estar creada y poblada con datos iniciales. 
-- TRANSACTION HANDLING:      
-- PERFORMANCE NOTE:          

------------------------------------------------------------------------------------------------------------------------
*/

-- -----------------------------------------------------
-- Table landing_scada_data
-- -----------------------------------------------------
CREATE TABLE stage.landing_scada_data (
    idn INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Registro incremental de tabla data, se ha cambiado por autoincremental para traer datos desde API REST
    unit_id INT, -- Este se mapeará a well_id
    location_id INT,
    var_id INT, -- ID de variable de scada tablar vars
    measure TEXT,
    moddate TIMESTAMP,
    modtime TIME
);
CREATE INDEX idx_landing_scada_data ON stage.landing_scada_data (unit_id, moddate);

-- -----------------------------------------------------
-- Table tbl_pozo_maestra
-- PK: well_id, UK: nombre_pozo
-- -----------------------------------------------------
CREATE TABLE stage.tbl_pozo_maestra (
    well_id INT PRIMARY KEY, -- ID: 1
    nombre_pozo VARCHAR(255) UNIQUE NOT NULL, -- ID: 49
    
    -- Identificación y Ubicación
    cliente VARCHAR(100), -- ID: 12
    pais VARCHAR(100), -- ID: 13
    region VARCHAR(100), -- ID: 14
    campo VARCHAR(100), -- ID: 15
    api_number VARCHAR(50), -- ID: 5
    coordenadas_pozo VARCHAR(100), -- ID: 4
    
    -- Completación y Geología
    tipo_pozo VARCHAR(100), -- ID: 3
    profundidad_completacion DECIMAL, -- ID: 2
    intervalo_disparos VARCHAR(100), -- ID: 26
    radio_pozo DECIMAL, -- ID: 19
    espesor_formacion DECIMAL, -- ID: 23
    nombre_yacimiento VARCHAR(100), -- ID: 16
    permeabilidad_abosluta DECIMAL, -- ID: 17
    permeabilidad_horizontal DECIMAL, -- ID: 28
    radio_drenaje DECIMAL, -- ID: 20
    
    -- Propiedades del Yacimiento (Iniciales / Estáticas)
    presion_inicial_yacimiento DECIMAL, -- ID: 21
    temperatura_yacimiento DECIMAL, -- ID: 22
    
    -- Equipos (Nominales)
    tipo_levantamiento VARCHAR(100), -- ID: 37
    profundidad_vertical_yacimiento DECIMAL, -- ID: 38
    profundidad_vertical_bomba DECIMAL, -- ID: 39
    diametro_embolo_bomba DECIMAL, -- ID: 33
    longitud_carrera_nominal DECIMAL, -- ID: 42
    potencia_nominal_motor DECIMAL, -- ID: 43
    corriente_nominal_motor DECIMAL, -- ID: 44
    voltaje_nominal DECIMAL, -- ID: 45
    frecuencia_nominal_motor DECIMAL, -- ID: 85
    carga_nominal_unidad DECIMAL, -- ID: 46
    carga_minima_nominal_sarta DECIMAL, -- ID: 47
    numero_software VARCHAR(50), -- ID: 87
    
    fecha_registro DATE NOT NULL, -- ID: 6
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- -----------------------------------------------------
-- Table tbl_pozo_reservas
-- PK: reserva_id, FK: well_id
-- -----------------------------------------------------
CREATE TABLE stage.tbl_pozo_reservas (
    reserva_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    well_id INT NOT NULL, -- ID: 1
    fecha_registro DATE NOT NULL, -- ID: 6
    
    -- Presiones y Fluidos
    gravedad_api DECIMAL, -- ID: 10
    viscosidad_crudo DECIMAL, -- ID: 18
    viscosidad_superficie DECIMAL, -- ID: 29
    presion_burbujeo DECIMAL, -- ID: 24
    presion_estatica_yacimiento DECIMAL, -- ID: 25
    factor_volumetrico DECIMAL, -- ID: 30
    gravedad_especifica_agua DECIMAL, -- ID: 63
    
    -- Propiedades Dinámicas/Calculadas
    permeabilidad_vertical DECIMAL, -- ID: 162
    radio_equivalente DECIMAL, -- ID: 159
    longitud_horizontal DECIMAL, -- ID: 160
    factor_dano DECIMAL, -- ID: 161
    
    -- Parámetros de Operación/Setpoints
    presion_fondo_fluyente_critico DECIMAL, -- ID: 27
    wc_critico DECIMAL, -- ID: 32
    llenado_bomba_minimo DECIMAL, -- ID: 48
    q_esperado DECIMAL, -- ID: 152
    reserva_inicial_teorica DECIMAL(14, 2), -- ID 128
    
    -- Misceláneos
    contenido_finos DECIMAL, -- ID: 58
    otros_pvt TEXT, -- ID: 31
    
    CONSTRAINT fk_pozo_reserva FOREIGN KEY (well_id) REFERENCES stage.tbl_pozo_maestra (well_id) ON DELETE CASCADE,
    CONSTRAINT uq_reserva_fecha_pozo UNIQUE (well_id, fecha_registro)
);

-- -----------------------------------------------------
-- Table tbl_pozo_produccion
-- PK: produccion_id, FK: well_id
-- -----------------------------------------------------
CREATE TABLE stage.tbl_pozo_produccion (
    produccion_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    well_id INT NOT NULL,
    timestamp_lectura TIMESTAMP NOT NULL, -- ID: 50
    
    -- Presiones y Temperaturas
    presion_cabezal DECIMAL, -- ID: 54 (WHP)
    presion_casing DECIMAL, -- ID: 55 (CHP)
    temperatura_cabezal DECIMAL, -- ID: 56 (THP)
    presion_descarga_bomba DECIMAL, -- ID: 62
    PIP DECIMAL, -- ID: 61
    temperatura_tanque_aceite DECIMAL, -- ID: 94
    presion_cilindro_hidraulico DECIMAL, -- ID: 93
    
    -- Producción y Fluidos (Diarios)
    produccion_fluido_diaria DECIMAL, -- ID: 107
    produccion_petroleo_diaria DECIMAL, -- ID: 108
    produccion_agua_diaria DECIMAL, -- ID: 109
    produccion_gas_diaria DECIMAL, -- ID: 110
    porcentaje_agua DECIMAL, -- ID: 57
    monitor_llenado_gas DECIMAL, -- ID: 96
    monitor_llenado_liquido DECIMAL, -- ID: 119
    fuga_diaria DECIMAL, -- ID: 113
    fluid_flow_monitor_bpd DECIMAL(10, 2), -- ID: 65
    
    -- Producción y Fluidos (Acumulados / Instantáneos)
    medidor_produccion_fluido DECIMAL, -- ID: 97
    produccion_petroleo_acumulada DECIMAL, -- ID: 98
    medidor_produccion_agua DECIMAL, -- ID: 99
    medidor_produccion_gas DECIMAL, -- ID: 100
    
    -- Operación y Monitoreo del Equipo
    spm_promedio DECIMAL, -- ID: 51
    spm_solicitado_arriba DECIMAL, -- ID: 52
    spm_solicitado_abajo DECIMAL, -- ID: 53
    nivel_fluido_flop DECIMAL, -- ID: 60
    pump_fill_monitor DECIMAL, -- ID: 64
    potencia_actual_motor DECIMAL, -- ID: 66
    current_amperage DECIMAL, -- ID: 67
    rpm_motor DECIMAL, -- ID: 86
    estado_motor BOOLEAN, -- ID: 120
    tiempo_actual_drive DECIMAL, -- ID: 95
    
    -- Cargas y Carreras
    longitud_carrera_nominal DECIMAL, -- ID: 122
    carrera_bomba_api DECIMAL, -- ID: 121
    peso_sarta_aire DECIMAL, -- ID: 72
    rod_weight_buoyant DECIMAL, -- ID: 73
    monitor_carga_bomba DECIMAL, -- ID: 74
    carga_maxima_fluido_api DECIMAL, -- ID: 75
    maximum_rod_load DECIMAL, -- ID: 76
    minimum_rod_load DECIMAL, -- ID: 77
    carga_caja_engranajes DECIMAL, -- ID: 79
    
    -- Indicadores de Eficiencia y POC
    kwh_por_barril DECIMAL, -- ID: 71
    eficiencia_levantamiento DECIMAL, -- ID: 118
    porcentaje_operacion_diario DECIMAL, -- ID: 106
    tiempo_parada_poc_diario DECIMAL, -- ID: 114
    conteo_poc_diario INT, -- ID: 115
    
    -- Sensores y Otros
    anchor_vertical_depth DECIMAL, -- ID: 78
    inclinacion_vastago DECIMAL, -- ID: 82
    inclinacion_cilindro_x DECIMAL, -- ID: 88
    inclinacion_cilindro_y DECIMAL, -- ID: 89
    alerta_inclinacion_grados DECIMAL, -- ID: 90
    falla_inclinacion_grados DECIMAL, -- ID: 91
    posicion_lineal DECIMAL, -- ID: 92
    
    -- Acumuladores y Contadores
    contador_emboladas INT, -- ID: 101
    horas_operacion_acumuladas DECIMAL, -- ID: 102
    tiempo_operacion_medidor_acum DECIMAL, -- ID: 103
    energia_medidor_acumulada DECIMAL, -- ID: 104
    emboladas_medidor_acumuladas INT, -- ID: 105
    emboladas_diarias INT, -- ID: 111
    llenado_promedio_diario DECIMAL, -- ID: 112
    potencia_medidor_diaria DECIMAL, -- ID: 116
    emboladas_arranque_poc INT, -- ID: 123
    emboladas_espera_poc INT, -- ID: 124
    conteo_poc_medidor_acum INT, -- ID: 125
    tiempo_parada_poc_medidor_acum DECIMAL, -- ID: 126
    spm_promedio_diario_medidor DECIMAL, -- ID: 127
    
    -- Tarjetas de Dinamómetro
    surface_rod_position TEXT, -- ID: 155
    surface_rod_load TEXT, -- ID: 156
    downhole_pump_position TEXT, -- ID: 157
    downhole_pump_load TEXT, -- ID: 158

    -- Misceeláneos
    nivel_fluido_dinamico DECIMAL, -- ID: 59
    
    CONSTRAINT fk_pozo_scada FOREIGN KEY (well_id) REFERENCES stage.tbl_pozo_maestra (well_id) ON DELETE CASCADE,
    CONSTRAINT uq_scada_timestamp_pozo UNIQUE (well_id, timestamp_lectura)
);

CREATE TABLE stage.tbl_pozo_scada_dq (
    dq_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    produccion_id BIGINT NOT NULL,
    timestamp_lectura TIMESTAMP NOT NULL,
    regla_rango_spm INTEGER,
    regla_no_cero_consumo INTEGER,
    regla_tolerancia_whp INTEGER,
    resultado_dq VARCHAR(20) NOT NULL,
    CONSTRAINT fk_scada_dq FOREIGN KEY (produccion_id) REFERENCES stage.tbl_pozo_produccion (produccion_id) ON DELETE CASCADE
);