CREATE TABLE tbl_pozo_maestra (
    well_id INT PRIMARY KEY,
    nombre_pozo VARCHAR(255) UNIQUE NOT NULL,
    cliente VARCHAR(100),
    region VARCHAR(100),
    campo VARCHAR(100),
    pais VARCHAR(100),
    tipo_pozo VARCHAR(100),
    coordenadas_pozo VARCHAR(100),
    well_api_number VARCHAR(50),
    profundidad_vertical_bomba_ft DECIMAL,
    profundidad_vertical_yacimiento_ft DECIMAL,
    profundidad_terminacion_ft DECIMAL,
    motor_rated_power_hp DECIMAL,
    motor_rated_current_amp DECIMAL,
    rated_voltage_volt DECIMAL,
    rated_stroke_length_in DECIMAL,
    rated_load_unit_lb DECIMAL,
    rated_min_rod_string_load_psi DECIMAL,
    diametro_piston_dp_in DECIMAL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tbl_pozo_reservas (
    reserva_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    well_id INT NOT NULL,
    fecha_medicion DATE NOT NULL,
    presion_estatica_yacimiento_psi DECIMAL,
    presion_actual_yacimiento_psi DECIMAL,
    presion_burbujeo_psi DECIMAL,
    temperatura_yacimiento_f DECIMAL,
    permeabilidad_horizontal DECIMAL,
    permeabilidad_vertical DECIMAL,
    viscosidad_crudo_cp DECIMAL,
    factor_volumetrico DECIMAL,
    gravedad_api DECIMAL,
    CONSTRAINT fk_pozo_reserva FOREIGN KEY (well_id) REFERENCES tbl_pozo_maestra (well_id) ON DELETE CASCADE,
    CONSTRAINT uq_reserva_fecha_pozo UNIQUE (well_id, fecha_medicion)
);

CREATE TABLE tbl_pozo_produccion (
    produccion_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    well_id INT NOT NULL,
    timestamp_lectura DATE NOT NULL,
    oil_production_bopd DECIMAL,
    water_production_bwpd DECIMAL,
    gas_production_mscfd DECIMAL,
    total_fluid_bpd DECIMAL,
    porcentaje_agua DECIMAL,
    pip_psi DECIMAL,
    CONSTRAINT fk_pozo_produccion FOREIGN KEY (well_id) REFERENCES tbl_pozo_maestra (well_id) ON DELETE CASCADE,
    CONSTRAINT uq_produccion_fecha_pozo UNIQUE (well_id, fecha)
);

CREATE TABLE tbl_pozo_operacion_scada (
    scada_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    well_id INT NOT NULL,
    timestamp_lectura TIMESTAMP NOT NULL,
    pump_avg_spm DECIMAL,
    current_hp_motor DECIMAL,
    whp_psi DECIMAL,
    pump_discharge_pressure_psi DECIMAL,
    current_amp_motor DECIMAL,
    current_surface_unit_stroke_in DECIMAL,
    pump_fill_monitor_pct DECIMAL,
    fluid_flow_monitor_bpd DECIMAL,
    rod_weight_in_air_lb DECIMAL,
    pump_load_monitor_lb DECIMAL,
    CONSTRAINT fk_pozo_scada FOREIGN KEY (well_id) REFERENCES tbl_pozo_maestra (well_id) ON DELETE CASCADE,
    CONSTRAINT uq_scada_timestamp_pozo UNIQUE (well_id, timestamp_lectura)
);

CREATE TABLE tbl_pozo_fallas (
    falla_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    well_id INT NOT NULL,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP,
    tipo_falla VARCHAR(100) NOT NULL,
    codigo_falla VARCHAR(50),
    descripcion_falla TEXT,
    tiempo_paro_hrs DECIMAL,
    es_paro_noprogramado INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_pozo_fallas FOREIGN KEY (well_id) REFERENCES tbl_pozo_maestra (well_id) ON DELETE CASCADE
);

CREATE TABLE tbl_pozo_scada_dq (
    dq_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    scada_id BIGINT NOT NULL,
    timestamp_lectura TIMESTAMP NOT NULL,
    regla_rango_spm INTEGER,
    regla_no_cero_consumo INTEGER,
    regla_tolerancia_whp INTEGER,
    resultado_dq VARCHAR(20) NOT NULL,
    CONSTRAINT fk_scada_dq FOREIGN KEY (scada_id) REFERENCES tbl_pozo_operacion_scada (scada_id) ON DELETE CASCADE
);