/*
------------------------------------------------------------------------------------------------------------------------
-- FILE NAME:                 V4__stage_schema_redesign.sql
-- DESCRIPTION:               Redesigned Stage Schema (V4). Limpieza total e ingesta.
------------------------------------------------------------------------------------------------------------------------
*/

DROP SCHEMA IF EXISTS stage CASCADE;
CREATE SCHEMA stage;

-- 1. LANDING
CREATE TABLE stage.landing_scada_data (
    idn INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id INT,
    location_id INT,
    var_id INT,
    measure TEXT,
    moddate TIMESTAMP,
    modtime TIME
);
CREATE INDEX idx_landing_scada_data ON stage.landing_scada_data (unit_id, moddate);

-- 2. MASTER POZO
CREATE TABLE stage.tbl_pozo_maestra (
    well_id INT PRIMARY KEY,
    nombre_pozo VARCHAR(255) UNIQUE NOT NULL,
    cliente VARCHAR(100),
    pais VARCHAR(100),
    region VARCHAR(100),
    campo VARCHAR(100),
    api_number VARCHAR(50),
    coordenadas_pozo VARCHAR(100),
    tipo_pozo VARCHAR(100),
    profundidad_completacion DECIMAL,
    intervalo_disparos VARCHAR(100),
    radio_pozo DECIMAL,
    espesor_formacion DECIMAL,
    nombre_yacimiento VARCHAR(100),
    permeabilidad_abosluta DECIMAL,
    permeabilidad_horizontal DECIMAL,
    radio_drenaje DECIMAL,
    presion_inicial_yacimiento DECIMAL,
    temperatura_yacimiento DECIMAL,
    tipo_levantamiento VARCHAR(100),
    profundidad_vertical_yacimiento DECIMAL,
    profundidad_vertical_bomba DECIMAL,
    diametro_embolo_bomba DECIMAL,
    longitud_carrera_nominal_unidad DECIMAL,
    potencia_nominal_motor DECIMAL,
    corriente_nominal_motor DECIMAL,
    voltaje_nominal DECIMAL,
    frecuencia_nominal_motor DECIMAL,
    carga_nominal_unidad DECIMAL,
    carga_minima_nominal_sarta DECIMAL,
    num_software VARCHAR(50),
    peso_sarta_aire DECIMAL,
    carga_maxima_fluido_api DECIMAL,
    fecha_registro DATE NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 3. RESERVAS
CREATE TABLE stage.tbl_pozo_reservas (
    reserva_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,     
    well_id INT NOT NULL,
    fecha_registro DATE NOT NULL,
    gravedad_api DECIMAL,
    viscosidad_crudo DECIMAL,
    viscosidad_superficie DECIMAL,
    presion_burbujeo DECIMAL,
    presion_estatica_yacimiento DECIMAL,
    factor_volumetrico DECIMAL,
    gravedad_especifica_agua DECIMAL,
    permeabilidad_vertical DECIMAL,
    radio_equivalente DECIMAL,
    longitud_horizontal DECIMAL,
    factor_dano DECIMAL,
    presion_fondo_fluyente_critico DECIMAL,
    wc_critico DECIMAL,
    llenado_bomba_minimo DECIMAL,
    q_esperado DECIMAL,
    reserva_inicial_teorica DECIMAL(14, 2),
    contenido_finos DECIMAL,
    otros_pvt TEXT,
    CONSTRAINT fk_pozo_reserva FOREIGN KEY (well_id) REFERENCES stage.tbl_pozo_maestra (well_id) ON DELETE CASCADE,
    CONSTRAINT uq_reserva_fecha_pozo UNIQUE (well_id, fecha_registro)    
);

-- 4. PRODUCCION (Tabla Ancha)
CREATE TABLE stage.tbl_pozo_produccion (
    produccion_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,  
    well_id INT NOT NULL,
    timestamp_lectura TIMESTAMP NOT NULL,
    presion_cabezal DECIMAL,
    presion_casing DECIMAL,
    temperatura_cabezal DECIMAL,
    presion_descarga_bomba DECIMAL,
    pip DECIMAL,
    temperatura_tanque_aceite DECIMAL,
    presion_cilindro_hidraulico DECIMAL,
    produccion_fluido_diaria DECIMAL,
    produccion_petroleo_diaria DECIMAL,
    produccion_agua_diaria DECIMAL,
    produccion_gas_diaria DECIMAL,
    porcentaje_agua DECIMAL,
    monitor_llenado_gas DECIMAL,
    monitor_llenado_liquido DECIMAL,
    fuga_diaria DECIMAL,
    fluid_flow_monitor_bpd DECIMAL(10, 2),
    medidor_produccion_fluido DECIMAL,
    produccion_petroleo_acumulada DECIMAL,
    medidor_produccion_agua DECIMAL,
    medidor_produccion_gas DECIMAL,
    spm_promedio DECIMAL,
    spm_solicitado_arriba DECIMAL,
    spm_solicitado_abajo DECIMAL,
    nivel_fluido_flop DECIMAL,
    pump_fill_monitor DECIMAL,
    potencia_actual_motor DECIMAL,
    current_amperage DECIMAL,
    rpm_motor DECIMAL,
    estado_motor BOOLEAN,
    tiempo_actual_drive DECIMAL,
    longitud_carrera_nominal DECIMAL,
    carrera_bomba_api DECIMAL,
    rod_weight_buoyant DECIMAL,
    monitor_carga_bomba DECIMAL,
    maximum_rod_load DECIMAL,
    minimum_rod_load DECIMAL,
    carga_caja_engranajes DECIMAL,
    kwh_por_barril DECIMAL,
    eficiencia_levantamiento DECIMAL,
    porcentaje_operacion_diario DECIMAL,
    tiempo_parada_poc_diario DECIMAL,
    conteo_poc_diario INT,
    anchor_vertical_depth DECIMAL,
    inclinacion_vastago DECIMAL,
    inclinacion_cilindro_x DECIMAL,
    inclinacion_cilindro_y DECIMAL,
    alerta_inclinacion_grados DECIMAL,
    falla_inclinacion_grados DECIMAL,
    posicion_lineal DECIMAL,
    contador_emboladas INT,
    horas_operacion_acumuladas DECIMAL,
    tiempo_operacion_medidor_acum DECIMAL,
    energia_medidor_acumulada DECIMAL,
    emboladas_medidor_acumuladas INT,
    emboladas_diarias INT,
    llenado_promedio_diario DECIMAL,
    potencia_medidor_diaria DECIMAL,
    emboladas_arranque_poc INT,
    emboladas_espera_poc INT,
    conteo_poc_medidor_acum INT,
    tiempo_parada_poc_medidor_acum DECIMAL,
    spm_promedio_diario_medidor DECIMAL,
    surface_rod_position TEXT,
    surface_rod_load TEXT,
    downhole_pump_position TEXT,
    downhole_pump_load TEXT,
    nivel_fluido_dinamico DECIMAL,
    CONSTRAINT fk_pozo_scada FOREIGN KEY (well_id) REFERENCES stage.tbl_pozo_maestra (well_id) ON DELETE CASCADE,
    CONSTRAINT uq_scada_timestamp_pozo UNIQUE (well_id, timestamp_lectura)
);

-- 5. DQ LOG
CREATE TABLE stage.tbl_pozo_scada_dq (
    dq_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    produccion_id BIGINT NOT NULL,
    timestamp_lectura TIMESTAMP NOT NULL,
    variable_id INT,
    regla_id INT,
    valor_observado DECIMAL,
    valor_esperado_min DECIMAL,
    valor_esperado_max DECIMAL,
    resultado_dq VARCHAR(20) DEFAULT 'FAIL',
    mensaje_error TEXT,
    CONSTRAINT fk_scada_dq FOREIGN KEY (produccion_id) REFERENCES stage.tbl_pozo_produccion (produccion_id) ON DELETE CASCADE
);