/*
------------------------------------------------------------------------------------------------------------------------
-- SCRIPT INFORMATION BLOCK
------------------------------------------------------------------------------------------------------------------------

-- FILE NAME:                 V4__stage_schema_redesign.sql
-- DESCRIPTION:               Stage Schema V4 — Esquema de staging para ingesta SCADA, producción,
--                            reservas y calidad de datos. Evolución de V3 con:
--                              • Campos estáticos (peso_sarta_aire, carga_maxima_fluido_api) movidos a maestra
--                              • DQ genérica (variable_id + regla_id) en vez de 3 columnas hardcoded
--                              • Nombre estandarizado: longitud_carrera_nominal_unidad_in
-- DATABASE PLATFORM:         PostgreSQL 15+
-- AUTHOR:                    ITMEET / ML Engineering Team
-- CREATION DATE:             2025-11-20 (V3) → 2026-01-15 (V4 redesign)

------------------------------------------------------------------------------------------------------------------------
-- VERSION CONTROL & HISTORY
------------------------------------------------------------------------------------------------------------------------

-- VERSION:                   4.0.0
-- LAST MODIFIED BY:          Pipeline Audit Agent
-- LAST MODIFIED DATE:        2026-02-15
-- CHANGE LOG:
--   V3 → V4:  peso_sarta_aire y carga_maxima_fluido_api movidos a tbl_pozo_maestra (datos estáticos)
--   V3 → V4:  tbl_pozo_scada_dq rediseñada: modelo genérico (variable_id, regla_id, valor_observado, rango)
--   V3 → V4:  longitud_carrera_nominal → longitud_carrera_nominal_unidad_in (incluye unidad)
--   V3 → V4:  numero_software → num_software (abreviado)
--   V4.1:     Restaurados comentarios ID formato1 y secciones de V3 para trazabilidad

------------------------------------------------------------------------------------------------------------------------
-- EXECUTION & DEPENDENCIES
------------------------------------------------------------------------------------------------------------------------

-- PRE-REQUISITES:            Ninguno — este script hace DROP CASCADE del schema stage completo.
-- DEPENDE DE:                Nada (se ejecuta primero en INIT).
-- CONSUMIDO POR:             ingest_real_telemetry.py, V1__stage_to_stage.sql (pivot EAV→wide),
--                            V6.1 (sp_load_to_reporting), V6.2 (DQ engine), V9 (derivados)
-- PERFORMANCE NOTE:          Índice compuesto (unit_id, moddate) en landing para pivot por hora.
--                            UNIQUE (well_id, timestamp_lectura) en producción para idempotencia.

------------------------------------------------------------------------------------------------------------------------
*/

DROP SCHEMA IF EXISTS stage CASCADE;
CREATE SCHEMA stage;

-- =====================================================
-- 1. LANDING SCADA (formato EAV desde API / dumps)
-- =====================================================
-- Tabla de aterrizaje cruda. Cada fila = 1 variable SCADA.
-- var_id corresponde al IDN nativo del controlador SCADA.
-- moddate = timestamp original de la lectura en campo.
CREATE TABLE stage.landing_scada_data (
    idn INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Autoincremental (API REST)
    unit_id INT,        -- Mapea a well_id vía tbl_pozo_maestra
    location_id INT,    -- ID de locación SCADA
    var_id INT,         -- IDN de variable SCADA (ver referencial.tbl_var_scada_map)
    measure TEXT,       -- Valor crudo (se castea en pivot)
    moddate TIMESTAMP,  -- Timestamp original de lectura en campo
    modtime TIME        -- Hora de modificación (redundante con moddate, legacy API)
);
CREATE INDEX idx_landing_scada_data ON stage.landing_scada_data (unit_id, moddate);

-- =====================================================
-- 2. MAESTRA DE POZOS (datos estáticos por pozo)
-- =====================================================
-- PK: well_id | UK: nombre_pozo
-- Contiene datos de diseño, ubicación y equipos que NO varían por lectura.
-- V4: peso_sarta_aire (ID:72) y carga_maxima_fluido_api (ID:75) movidos aquí desde producción.
CREATE TABLE stage.tbl_pozo_maestra (
    well_id INT PRIMARY KEY,                              -- ID: 1
    nombre_pozo VARCHAR(255) UNIQUE NOT NULL,              -- ID: 49

    -- Identificación y Ubicación
    cliente VARCHAR(100),                                  -- ID: 12
    pais VARCHAR(100),                                     -- ID: 13
    region VARCHAR(100),                                   -- ID: 14
    campo VARCHAR(100),                                    -- ID: 15
    api_number VARCHAR(50),                                -- ID: 5
    coordenadas_pozo VARCHAR(100),                         -- ID: 4

    -- Completación y Geología
    tipo_pozo VARCHAR(100),                                -- ID: 3
    profundidad_completacion DECIMAL,                      -- ID: 2
    intervalo_disparos VARCHAR(100),                       -- ID: 26
    radio_pozo DECIMAL,                                    -- ID: 19
    espesor_formacion DECIMAL,                             -- ID: 23
    nombre_yacimiento VARCHAR(100),                        -- ID: 16
    permeabilidad_abosluta DECIMAL,                        -- ID: 17
    permeabilidad_horizontal DECIMAL,                      -- ID: 28
    radio_drenaje DECIMAL,                                 -- ID: 20

    -- Propiedades del Yacimiento (Iniciales / Estáticas)
    presion_inicial_yacimiento DECIMAL,                    -- ID: 21
    temperatura_yacimiento DECIMAL,                        -- ID: 22

    -- Equipos (Nominales)
    tipo_levantamiento VARCHAR(100),                       -- ID: 37
    profundidad_vertical_yacimiento DECIMAL,               -- ID: 38
    profundidad_vertical_bomba DECIMAL,                    -- ID: 39
    diametro_embolo_bomba DECIMAL,                         -- ID: 33
    longitud_carrera_nominal_unidad_in DECIMAL,            -- ID: 42 (V4: renombrado, incluye unidad)
    potencia_nominal_motor DECIMAL,                        -- ID: 43
    corriente_nominal_motor DECIMAL,                       -- ID: 44
    voltaje_nominal DECIMAL,                               -- ID: 45
    frecuencia_nominal_motor DECIMAL,                      -- ID: 85
    carga_nominal_unidad DECIMAL,                          -- ID: 46
    carga_minima_nominal_sarta DECIMAL,                    -- ID: 47
    num_software VARCHAR(50),                              -- ID: 87 (V4: abreviado)

    -- Campos estáticos movidos desde tbl_pozo_produccion en V4
    peso_sarta_aire DECIMAL,                               -- ID: 72 (V3: estaba en producción)
    carga_maxima_fluido_api DECIMAL,                        -- ID: 75 (V3: estaba en producción)

    fecha_registro DATE NOT NULL,                          -- ID: 6
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- 3. RESERVAS (propiedades PVT y parámetros de operación)
-- =====================================================
-- PK: reserva_id | FK: well_id | UK: (well_id, fecha_registro)
CREATE TABLE stage.tbl_pozo_reservas (
    reserva_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    well_id INT NOT NULL,                                  -- ID: 1
    fecha_registro DATE NOT NULL,                          -- ID: 6

    -- Presiones y Fluidos
    gravedad_api DECIMAL,                                  -- ID: 10
    viscosidad_crudo DECIMAL,                              -- ID: 18
    viscosidad_superficie DECIMAL,                         -- ID: 29
    presion_burbujeo DECIMAL,                              -- ID: 24
    presion_estatica_yacimiento DECIMAL,                   -- ID: 25
    factor_volumetrico DECIMAL,                            -- ID: 30
    gravedad_especifica_agua DECIMAL,                      -- ID: 63

    -- Propiedades Dinámicas / Calculadas
    permeabilidad_vertical DECIMAL,                        -- ID: 162
    radio_equivalente DECIMAL,                             -- ID: 159
    longitud_horizontal DECIMAL,                           -- ID: 160
    factor_dano DECIMAL,                                   -- ID: 161

    -- Parámetros de Operación / Setpoints
    presion_fondo_fluyente_critico DECIMAL,                -- ID: 27
    wc_critico DECIMAL,                                    -- ID: 32
    llenado_bomba_minimo DECIMAL,                          -- ID: 48
    q_esperado DECIMAL,                                    -- ID: 152
    reserva_inicial_teorica DECIMAL(14, 2),                -- ID: 128

    -- Misceláneos
    contenido_finos DECIMAL,                               -- ID: 58
    otros_pvt TEXT,                                         -- ID: 31

    CONSTRAINT fk_pozo_reserva FOREIGN KEY (well_id) REFERENCES stage.tbl_pozo_maestra (well_id) ON DELETE CASCADE,
    CONSTRAINT uq_reserva_fecha_pozo UNIQUE (well_id, fecha_registro)
);

-- =====================================================
-- 4. PRODUCCIÓN — Tabla Ancha (pivot de landing EAV)
-- =====================================================
-- PK: produccion_id | FK: well_id | UK: (well_id, timestamp_lectura)
-- Cada fila = snapshot de ~70 variables SCADA para 1 pozo en 1 timestamp.
-- V4: peso_sarta_aire (ID:72) y carga_maxima_fluido_api (ID:75) movidos a maestra.
-- IDs corresponden a id_formato1 del catálogo de variables.
CREATE TABLE stage.tbl_pozo_produccion (
    produccion_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    well_id INT NOT NULL,
    timestamp_lectura TIMESTAMP NOT NULL,                  -- ID: 50 — Timestamp de lectura SCADA

    -- Presiones y Temperaturas
    presion_cabezal DECIMAL,                               -- ID: 54 | WHP (Well Head Pressure)
    presion_casing DECIMAL,                                -- ID: 55 | CHP (Casing Head Pressure)
    temperatura_cabezal DECIMAL,                           -- ID: 56 | THP (Tubing Head Temperature)
    presion_descarga_bomba DECIMAL,                        -- ID: 62 | PDP (Pump Discharge Pressure)
    pip DECIMAL,                                           -- ID: 61 | PIP (Pump Intake Pressure)
    temperatura_tanque_aceite DECIMAL,                     -- ID: 94 | Oil Tank Temperature
    presion_cilindro_hidraulico DECIMAL,                   -- ID: 93 | Hydraulic Cylinder Pressure

    -- Producción y Fluidos (Diarios)
    produccion_fluido_diaria DECIMAL,                      -- ID: 107 | Daily Fluid Production
    produccion_petroleo_diaria DECIMAL,                    -- ID: 108 | Daily Oil Production
    produccion_agua_diaria DECIMAL,                        -- ID: 109 | Daily Water Production
    produccion_gas_diaria DECIMAL,                         -- ID: 110 | Daily Gas Production
    porcentaje_agua DECIMAL,                               -- ID: 57  | Water Cut %
    monitor_llenado_gas DECIMAL,                           -- ID: 96  | Gas Fill Monitor
    monitor_llenado_liquido DECIMAL,                       -- ID: 119 | Liquid Fill Monitor
    fuga_diaria DECIMAL,                                   -- ID: 113 | Daily Leakage
    fluid_flow_monitor_bpd DECIMAL(10, 2),                 -- ID: 65  | Fluid Flow Monitor (formato1, sin IDN SCADA)

    -- Producción y Fluidos (Acumulados / Instantáneos)
    medidor_produccion_fluido DECIMAL,                     -- ID: 97  | Fluid Production Meter (accum)
    produccion_petroleo_acumulada DECIMAL,                 -- ID: 98  | Accum Oil (Np)
    medidor_produccion_agua DECIMAL,                       -- ID: 99  | Water Production Meter (accum)
    medidor_produccion_gas DECIMAL,                        -- ID: 100 | Gas Production Meter (accum)

    -- Operación y Monitoreo del Equipo
    spm_promedio DECIMAL,                                  -- ID: 51  | Pump Average SPM
    spm_solicitado_arriba DECIMAL,                         -- ID: 52  | Request SPM Up
    spm_solicitado_abajo DECIMAL,                          -- ID: 53  | Request SPM Down
    nivel_fluido_flop DECIMAL,                             -- ID: 60  | FLOP (Fluid Level Over Pump)
    pump_fill_monitor DECIMAL,                             -- ID: 64  | Pump Fill Monitor
    potencia_actual_motor DECIMAL,                         -- ID: 66  | Current HP Motor
    current_amperage DECIMAL,                              -- ID: 67  | Current AMP Motor
    rpm_motor DECIMAL,                                     -- ID: 86  | Motor RPM
    estado_motor BOOLEAN,                                  -- ID: 120 | Motor ON Status
    tiempo_actual_drive DECIMAL,                           -- ID: 95  | Drive Current Time

    -- Cargas y Carreras
    longitud_carrera_nominal_unidad_in DECIMAL,            -- ID: 42  | Unit RTD Stroke (V4: renombrado con unidad)
    carrera_bomba_api DECIMAL,                             -- ID: 121 | API Pump Stroke
    rod_weight_buoyant DECIMAL,                            -- ID: 73  | Rod Weight Buoyant
    monitor_carga_bomba DECIMAL,                           -- ID: 74  | Pump Load Monitor
    maximum_rod_load DECIMAL,                              -- ID: 76  | Maximum Rod Load
    minimum_rod_load DECIMAL,                              -- ID: 77  | Minimum Rod Load
    carga_caja_engranajes DECIMAL,                         -- ID: 79  | Gearbox Load %

    -- Indicadores de Eficiencia y POC
    kwh_por_barril DECIMAL,                                -- ID: 71  | KWh/Bbl
    eficiencia_levantamiento DECIMAL,                      -- ID: 118 | Lift Efficiency
    porcentaje_operacion_diario DECIMAL,                   -- ID: 106 | Daily Run %
    tiempo_parada_poc_diario DECIMAL,                      -- ID: 114 | Daily POC Down Time
    conteo_poc_diario INT,                                 -- ID: 115 | Daily POC Count

    -- Sensores y Otros
    anchor_vertical_depth DECIMAL,                         -- ID: 78  | Anchor Vertical Depth
    inclinacion_vastago DECIMAL,                           -- ID: 82  | Stem Tilt
    inclinacion_cilindro_x DECIMAL,                        -- ID: 88  | Cylinder Tilt X
    inclinacion_cilindro_y DECIMAL,                        -- ID: 89  | Cylinder Tilt Y
    alerta_inclinacion_grados DECIMAL,                     -- ID: 90  | Cyl Tilt Warn Deg
    falla_inclinacion_grados DECIMAL,                      -- ID: 91  | Cyl Tilt Fault Deg
    posicion_lineal DECIMAL,                               -- ID: 92  | Linear Position

    -- Acumuladores y Contadores
    contador_emboladas INT,                                -- ID: 101 | Pump Stroke Counter
    horas_operacion_acumuladas DECIMAL,                    -- ID: 102 | Cumulative Run Hours
    tiempo_operacion_medidor_acum DECIMAL,                 -- ID: 103 | Gauge Run Time Accum
    energia_medidor_acumulada DECIMAL,                     -- ID: 104 | Gauge Power Meter Accum
    emboladas_medidor_acumuladas INT,                      -- ID: 105 | Gauge Strokes Accum
    emboladas_diarias INT,                                 -- ID: 111 | Daily Strokes
    llenado_promedio_diario DECIMAL,                       -- ID: 112 | Daily Avg Fill
    potencia_medidor_diaria DECIMAL,                       -- ID: 116 | Gauge Power Meter Daily
    emboladas_arranque_poc INT,                            -- ID: 123 | POC Powerup Strokes
    emboladas_espera_poc INT,                              -- ID: 124 | POC Standby Strokes
    conteo_poc_medidor_acum INT,                           -- ID: 125 | Gauge POC Count Accum
    tiempo_parada_poc_medidor_acum DECIMAL,                -- ID: 126 | Gauge POC Down Time Accum
    spm_promedio_diario_medidor DECIMAL,                   -- ID: 127 | Daily Gauge Avg SPM

    -- Tarjetas de Dinamómetro (arrays serializados)
    surface_rod_position TEXT,                              -- ID: 155 | Current Inch Surface Card
    surface_rod_load TEXT,                                  -- ID: 156 | Current Lb Surface Card
    downhole_pump_position TEXT,                            -- ID: 157 | Current Inch Downhole Pump Card
    downhole_pump_load TEXT,                                -- ID: 158 | Current Lb Downhole Pump Card

    -- Misceláneos
    nivel_fluido_dinamico DECIMAL,                         -- ID: 59  | Fluid Level TVD, ft

    CONSTRAINT fk_pozo_scada FOREIGN KEY (well_id) REFERENCES stage.tbl_pozo_maestra (well_id) ON DELETE CASCADE,
    CONSTRAINT uq_scada_timestamp_pozo UNIQUE (well_id, timestamp_lectura)
);

-- =====================================================
-- 5. DATA QUALITY LOG — Modelo Genérico Normalizado
-- =====================================================
-- V3 usaba 3 columnas hardcoded (spm_valid, motor_hp_valid, whp_valid)
-- con reglas CASE embebidas en transform_stage_DQ.sql.
-- V4 reemplaza con modelo EAV: cada fila = 1 validación de 1 variable,
-- extensible vía referencial.tbl_dq_rules sin cambios DDL.
-- FK: produccion_id → tbl_pozo_produccion | variable_id → catálogo formato1
CREATE TABLE stage.tbl_pozo_scada_dq (
    dq_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    produccion_id BIGINT NOT NULL,                         -- FK a tbl_pozo_produccion
    timestamp_lectura TIMESTAMP NOT NULL,                  -- Copia de produccion.timestamp_lectura
    variable_id INT,                                       -- ID formato1 de la variable evaluada
    regla_id INT,                                          -- ID de la regla DQ aplicada
    valor_observado DECIMAL,                               -- Valor real de la variable
    valor_esperado_min DECIMAL,                            -- Umbral inferior de la regla
    valor_esperado_max DECIMAL,                            -- Umbral superior de la regla
    resultado_dq VARCHAR(20) DEFAULT 'FAIL',               -- PASS | FAIL | WARNING
    mensaje_error TEXT,                                    -- Descripción del fallo
    CONSTRAINT fk_scada_dq FOREIGN KEY (produccion_id) REFERENCES stage.tbl_pozo_produccion (produccion_id) ON DELETE CASCADE
);